### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by CoderAryanAnand** [CoderAryanAnand/BackendKantiBaden#2]
### Frontend: -- HTML / CSS -- Make modules for:

- [ ] Request to API for Data retrieval
- [x] Login
- [x] Account Creation

### Backend: API 

- [ ] Normal Data retrieval
- [x] Login: Compare entered password with listed password of account in Database
- [x] Register: Pass on to Database

### Database

- [x] Create new account
- [ ] Retrieve a specific segment of data from x Account
- [ ] Overwrite a specific segment of data at x Account
- [ ] Delete an Account?
